[package]
name = "deepwiki-rs"
version = "1.5.0"
edition = "2024"

description = "deepwiki-rs(also known as Litho) is a high-performance automatic generation engine for C4 architecture documentation, developed using Rust. It can intelligently analyze project structures, identify core components, parse dependency relationships, and leverage large language models (LLMs) to automatically generate professional architecture documentation."
license = "MIT"
repository = "https://github.com/sopaco/deepwiki-rs"

[dependencies]
# rig
rig-core = "0.35"

# networking
reqwest = { version = "0.12", features = ["json"] }

# async runtime
tokio = { version = "1.47", features = ["full"] }

# error handling
anyhow = "1.0"
thiserror = "2.0"

# serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "1"

# CLI parsing
clap = { version = "4.5", features = ["derive"] }

# config parsing
toml = "0.9"

# date/time
chrono = { version = "0.4", features = ["serde"] }

# file traversal
walkdir = "2.5"

# regex
regex = "1.11"

# hashing
md-5 = "0.10"

# Base64 encoding
base64 = "0.22"

# PDF parsing
pdf-extract = "0.7"

# misc utilities
async-trait = "0.1"
rand = "0.9"
pathdiff = "0.2.3"
markdown = "1.0"
futures = "0.3"
uuid = { version = "1.0", features = ["v4", "serde"] }
glob = "0.3"
mermaid-fixer = { path = "mermaid-fixer" }
